### ISSUE TITLE
SLE12 support

### ISSUE THREAD

**Issue by asvetter** [thkukuk/os-update#10]
Is SLE12 support worth the effort?

- zypper in SLE 12 does not remember if reboot is needed. I could write something along that lines:
    * use uname -r to determine kernel flavour and version
    * compare $version to installed versions from rpm -qa kernel-$flavour
    * trigger reboot or not
-  copy needs-restarting from newer zypper

Or bring a newer zypper to SLE12?

**Comment by thkukuk** [comment]
Is available since version 1.9
