### ISSUE TITLE
handling reboot, when dbus needs restart

### ISSUE THREAD

**Issue by asvetter** [thkukuk/os-update#2]
Situation: When a library is updated, that is used by dbus, dbus can't be restarted. Right now (up to 1.6) this is not handled.
Solution: I think we should trigger a reboot in this case.

I see 3 ways to do that:
1. Hardcode that $(zypper ps -sss) containing dbus should trigger a reboot
    Possible problem: hardcoding  might be a problem later, when another service cannot be restarted
2. Use the list in $IGNORE_SERVICES_FROM_RESTART
    Possible problem: The user (admin) might want to have display-manager on the list and not reboot. On the other hand the system is rebooted because of dbus, so no problem?
3. Introduce a new variable with list of services, e.g. SERVICE_TRIGGERING_REBOOT
    Might be overkill

What do you think? I will code something in the "right" direction.

**Comment by asvetter** [comment]
done. included in version 1.6

**Comment by asvetter** [comment]
Closed by accident. Reopening. 
Sorry

**Comment by thkukuk** [comment]
You could have closed it, PR got accepted
